apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: video-service
---
apiVersion: v1
kind: Service
metadata:
  name: video-mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-service
  labels:
    app: video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
        - name: video-service
          image: datuits/devops-video-service:latest
          ports:
            - containerPort: 8083
          env:
          - name: SPRING_DATA_MONGODB_URI
            value: mongodb://video-mongo-service:27017/video-service
---
apiVersion: v1
kind: Service
metadata:
  name: video-service
spec:
  selector:
    app: video-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP