name: Continuous Integration for Video Service

on:
  push:
    branches:
      - test

jobs:
  testing:
    name: Testing Video Service
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Set up MongoDB URI
        run: echo "SPRING_DATA_MONGODB_URI=mongodb://localhost:27017/video-service" >> $GITHUB_ENV

      - name: Unit Tests
        run: mvn -B test --file pom.xml

  sonar_cloud_scan:
    needs: testing
    uses: ./.github/workflows/SonarQube.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  scan-image:
    needs: sonar_cloud_scan
    uses: ./.github/workflows/scan-image.yaml

  notify:
    needs: scan-image
    uses: ./.github/workflows/notifyCI.yaml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}